# Generated by Django 4.2.11 on 2024-06-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phonenumber",
            field=models.CharField(max_length=20),
        ),
    ]
